export const business = [
  {
    label: '西城区',
    value: '西城区',
    children: [
      { label: '西单', value: 338 },
      { label: '复兴门', value: 339 },
      { label: '阜成门', value: 340 },
      { label: '西直门/动物园', value: 341 },
      { label: '新街口', value: 342 },
      { label: '地安门', value: 343 },
      { label: '牛街', value: 344 },
      { label: '虎坊桥', value: 345 },
      { label: '菜市口/陶然亭', value: 346 },
      { label: '广内大街', value: 347 },
      { label: '宣武门', value: 348 },
      { label: '右安门', value: 349 },
      { label: '广外大街', value: 350 },
      { label: '前门/大栅栏', value: 351 },
      { label: '西四', value: 352 },
      { label: '月坛', value: 353 },
      { label: '后海/什刹海', value: 354 },
      { label: '德外大街', value: 355 },
      { label: '南菜园/白纸坊', value: 356 },
      { label: '长椿街', value: 357 },
      { label: '西便门', value: 358 },
      { label: '金融街', value: 359 },
      { label: '和平门', value: 360 },
      { label: '首都博物馆/莲花池东路', value: 361 },
      { label: '前门/天坛', value: 362 },
      { label: '东花园', value: 363 },
    ],
  },
  {
    label: '平谷区',
    value: '平谷区',
    children: [{ label: '平谷区', value: 498 }],
  },
  {
    label: '门头沟区',
    value: '门头沟区',
    children: [{ label: '门头沟区', value: 497 }],
  },
  {
    label: '密云区',
    value: '密云区',
    children: [
      { label: '密云镇', value: 492 },
      { label: '十里堡镇', value: 493 },
      { label: '溪翁庄镇', value: 494 },
      { label: '密云区其他', value: 495 },
    ],
  },
  {
    label: '顺义区',
    value: '顺义区',
    children: [
      { label: '石园', value: 479 },
      { label: '首都机场', value: 480 },
      { label: '国展', value: 481 },
      { label: '顺义', value: 482 },
      { label: '后沙峪', value: 483 },
      { label: '马坡牛栏山镇', value: 484 },
      { label: '南彩镇', value: 485 },
      { label: '莲花山滑雪场', value: 486 },
      { label: '小汤山/央美博艺艺术馆', value: 487 },
      { label: '天竺', value: 488 },
      { label: '首都机场T3航站楼', value: 489 },
      { label: '首都机场/机场路', value: 490 },
    ],
  },
  {
    label: '朝阳区',
    value: '朝阳区',
    children: [
      { label: '建外大街', value: 251 },
      { label: '大望路', value: 252 },
      { label: '左家庄', value: 253 },
      { label: '亮马桥/三元桥', value: 254 },
      { label: '亚运村', value: 255 },
      { label: '望京', value: 256 },
      { label: '劲松/潘家园', value: 257 },
      { label: '安贞', value: 258 },
      { label: '芍药居', value: 259 },
      { label: '朝阳公园/团结湖', value: 260 },
      { label: '国贸/建外', value: 261 },
      { label: '双井', value: 262 },
      { label: '三里屯/工体', value: 263 },
      { label: '对外经贸', value: 264 },
      { label: '酒仙桥', value: 265 },
      { label: '管庄', value: 266 },
      { label: '十八里店', value: 267 },
      { label: '北苑家园', value: 268 },
      { label: '十里堡', value: 269 },
      { label: '东坝', value: 270 },
      { label: '孙河', value: 271 },
      { label: '马泉营', value: 272 },
      { label: '定福庄', value: 273 },
      { label: '四惠', value: 274 },
      { label: '太阳宫', value: 275 },
      { label: '青年路', value: 276 },
      { label: '石佛营', value: 277 },
      { label: '甜水园', value: 278 },
      { label: '慈云寺/八里庄', value: 279 },
      { label: '工人体育场', value: 280 },
      { label: '百子湾', value: 281 },
      { label: '传媒大学/二外', value: 282 },
      { label: '双桥', value: 283 },
      { label: '北京欢乐谷', value: 284 },
      { label: '高碑店', value: 285 },
      { label: '北京东站', value: 286 },
      { label: '三元桥/霄云路', value: 287 },
      { label: '蓝色港湾', value: 288 },
      { label: '姚家园', value: 289 },
      { label: '十里河', value: 290 },
      { label: '立水桥', value: 291 },
      { label: '小营', value: 292 },
      { label: '北沙滩', value: 293 },
      { label: '大屯', value: 294 },
      { label: '小庄/红庙', value: 295 },
      { label: '常营', value: 296 },
      { label: '798/大山子', value: 297 },
      { label: '草房', value: 298 },
      { label: '东大桥', value: 299 },
      { label: '小红门', value: 300 },
      { label: '广渠门外', value: 301 },
      { label: '王四营', value: 302 },
      { label: '金盏', value: 303 },
      { label: '五方桥', value: 304 },
      { label: '朝阳大悦城', value: 305 },
      { label: '燕莎', value: 306 },
      { label: '农业展览馆', value: 307 },
      { label: '悠唐生活广场', value: 308 },
      { label: '鸟巢/水立方', value: 309 },
      { label: '西直河', value: 310 },
      { label: '善各庄', value: 311 },
      { label: '朝外大街', value: 312 },
      { label: '分钟寺/成寿寺', value: 313 },
    ],
  },
  {
    label: '怀柔区',
    value: '怀柔区',
    children: [{ label: '怀柔区', value: 496 }],
  },
  {
    label: '房山区',
    value: '房山区',
    children: [
      { label: '城关街道', value: 463 },
      { label: '窦店镇', value: 464 },
      { label: '阎村镇', value: 465 },
      { label: '燕山', value: 466 },
      { label: '河北镇', value: 467 },
      { label: '十渡镇', value: 468 },
      { label: '青龙湖镇', value: 469 },
      { label: '良乡', value: 470 },
      { label: '长阳镇', value: 471 },
      { label: '仙栖洞', value: 472 },
      { label: '上方山国家森林公园', value: 473 },
      { label: '云居滑雪场', value: 474 },
      { label: '霞云岭国家森林公园', value: 475 },
      { label: '华冠天地', value: 476 },
      { label: '孤山寨', value: 477 },
      { label: '东湖港', value: 478 },
    ],
  },
  {
    label: '大兴区',
    value: '大兴区',
    children: [
      { label: '亦庄', value: 427 },
      { label: '旧宫', value: 428 },
      { label: '黄村', value: 429 },
      { label: '西红门', value: 430 },
      { label: '庞各庄', value: 431 },
      { label: '龙湖天街购物中心', value: 432 },
      { label: '南苑/德茂桥', value: 433 },
    ],
  },
  {
    label: '丰台区',
    value: '丰台区',
    children: [
      { label: '六里桥/丽泽桥', value: 396 },
      { label: '洋桥/木樨园', value: 397 },
      { label: '方庄/蒲黄榆', value: 398 },
      { label: '北大地/万丰路', value: 399 },
      { label: '刘家窑/宋家庄', value: 400 },
      { label: '青塔', value: 401 },
      { label: '北京南站/开阳里', value: 402 },
      { label: '草桥/公益西桥', value: 403 },
      { label: '看丹桥/新华街', value: 404 },
      { label: '花乡/新发地', value: 405 },
      { label: '大红门', value: 406 },
      { label: '云岗', value: 407 },
      { label: '卢沟桥', value: 408 },
      { label: '北京西站/六里桥', value: 409 },
      { label: '分钟寺/成寿寺', value: 410 },
      { label: '夏家胡同/纪家庙', value: 411 },
      { label: '马家堡/角门', value: 412 },
      { label: '丽泽桥/丰管路', value: 413 },
      { label: '总部基地', value: 414 },
      { label: '石榴庄', value: 415 },
      { label: '槐房万达广场', value: 416 },
      { label: '世界公园', value: 417 },
      { label: '南苑/东高地', value: 418 },
      { label: '南宫', value: 419 },
      { label: '右安门', value: 420 },
      { label: '南苑/德茂桥', value: 421 },
    ],
  },
  {
    label: '石景山区',
    value: '石景山区',
    children: [
      { label: '苹果园', value: 422 },
      { label: '古城/八角', value: 423 },
      { label: '鲁谷', value: 424 },
      { label: '模式口', value: 425 },
      { label: '八大处', value: 426 },
    ],
  },
  {
    label: '东城区',
    value: '东城区',
    children: [
      { label: '王府井/东单', value: 314 },
      { label: '建国门/北京站', value: 315 },
      { label: '东四', value: 316 },
      { label: '安定门', value: 317 },
      { label: '朝阳门', value: 318 },
      { label: '东直门', value: 319 },
      { label: '广渠门内', value: 320 },
      { label: '左安门', value: 321 },
      { label: '沙子口', value: 322 },
      { label: '崇文门', value: 323 },
      { label: '天坛', value: 324 },
      { label: '地安门', value: 325 },
      { label: '广渠门外', value: 326 },
      { label: '和平里/国展中心', value: 327 },
      { label: '东花园', value: 328 },
      { label: '东四十条', value: 329 },
      { label: '雍和宫/地坛', value: 330 },
      { label: '南锣鼓巷/鼓楼东大街', value: 331 },
      { label: '北新桥/簋街', value: 332 },
      { label: '光明楼/龙潭湖', value: 333 },
      { label: '沙滩/美术馆', value: 334 },
      { label: '王府井/前门', value: 335 },
      { label: '南锣古巷/鼓楼后海', value: 336 },
      { label: '天安门广场', value: 337 },
    ],
  },
  {
    label: '昌平区',
    value: '昌平区',
    children: [
      { label: '回龙观', value: 451 },
      { label: '天通苑', value: 452 },
      { label: '昌平镇', value: 453 },
      { label: '小汤山镇', value: 454 },
      { label: '南口镇', value: 455 },
      { label: '北七家', value: 456 },
      { label: '沙河', value: 457 },
      { label: '明十三陵', value: 458 },
      { label: '居庸关长城', value: 459 },
      { label: '十三陵水库', value: 460 },
      { label: '小汤山', value: 461 },
      { label: '蟒山国家森林公园', value: 462 },
    ],
  },
  {
    label: '海淀区',
    value: '海淀区',
    children: [
      { label: '中关村', value: 364 },
      { label: '魏公村', value: 365 },
      { label: '苏州桥', value: 366 },
      { label: '北下关', value: 367 },
      { label: '公主坟/万寿路', value: 368 },
      { label: '紫竹桥', value: 369 },
      { label: '上地', value: 370 },
      { label: '颐和园', value: 371 },
      { label: '田村', value: 372 },
      { label: '五道口', value: 373 },
      { label: '牡丹园/北太平庄', value: 374 },
      { label: '航天桥', value: 375 },
      { label: '双榆树', value: 376 },
      { label: '五棵松', value: 377 },
      { label: '清河', value: 378 },
      { label: '远大路', value: 379 },
      { label: '香山/植物园', value: 380 },
      { label: '大钟寺', value: 381 },
      { label: '知春路', value: 382 },
      { label: '西三旗', value: 383 },
      { label: '四季青', value: 384 },
      { label: '人民大学', value: 385 },
      { label: '万柳', value: 386 },
      { label: '学院桥/学院路', value: 387 },
      { label: '北京西站/军博', value: 388 },
      { label: '农业大学西区', value: 389 },
      { label: '甘家口百货', value: 390 },
      { label: '百望山森林公园/309医院', value: 391 },
      { label: '上庄', value: 392 },
      { label: '北京大学', value: 393 },
      { label: '西北旺', value: 394 },
      { label: '北沙滩', value: 395 },
    ],
  },
  {
    label: '延庆区',
    value: '延庆区',
    children: [{ label: '延庆区其他', value: 491 }],
  },
  {
    label: '通州区',
    value: '通州区',
    children: [
      { label: '宋庄', value: 434 },
      { label: '西集', value: 435 },
      { label: '物资学院', value: 436 },
      { label: '果园', value: 437 },
      { label: '梨园', value: 438 },
      { label: '新华大街', value: 439 },
      { label: '九棵树', value: 440 },
      { label: '通州北苑', value: 441 },
      { label: '武夷花园', value: 442 },
      { label: '马驹桥', value: 443 },
      { label: '次渠', value: 444 },
      { label: '北关', value: 445 },
      { label: '土桥', value: 446 },
      { label: '白庙', value: 447 },
      { label: '新华联', value: 448 },
      { label: '八里桥', value: 449 },
      { label: '开发区', value: 450 },
    ],
  },
]
