import { Config } from '@tarojs/taro'

export default {
  pages: [
    'pages/Index/Index',
    'pages/ComponentList/ComponentList',
    'pages/Login/Login',
    'pages/Demo/Demo',
    'pages/Icon/Icon',
    'pages/Input/Input',
    'pages/Form/Form',
    'pages/TextArea/TextArea',
    'pages/Switch/Switch',
    'pages/Checkbox/Checkbox',
    'pages/Radio/Radio',
    'pages/Tabs/Tabs',
    'pages/Sticky/Sticky',
    'pages/Tag/Tag',
    'pages/List/List',
    'pages/ContentList/ContentList',
    'pages/Grid/Grid',
    'pages/Stepper/Stepper',
    'pages/SwiperIndicator/SwiperIndicator',
    'pages/Badge/Badge',
    'pages/NoticeBar/NoticeBar',
    'pages/Image/Image',
    'pages/Avatar/Avatar',
    'pages/Modal/Modal',
    'pages/Search/Search',
    'pages/Select/Select',

    'pages/Color/Color',
    'pages/Text/Text',
    'pages/Layer/Layer',
    'pages/Button/Button',
    'pages/Divider/Divider',
    'pages/Popup/Popup',
    'pages/DefaultPage/DefaultPage',
    'pages/DefaultPageDetail/DefaultPageDetail',
    'pages/Loader/Loader',
    'pages/LoaderDetail/LoaderDetail',
    'pages/Picker/Picker',
    'pages/Tooltip/Tooltip',
    'pages/ActionSheet/ActionSheet',
    'pages/ToastPage/ToastPage',
    'pages/Dialog/Dialog',
    'pages/Team/Team',
    'pages/Share/Share',
    'pages/Timer/Timer',
    'pages/Footer/Footer',
    'pages/Skeleton/Skeleton',
    'pages/NavBar/NavBar',
    'pages/NavBarBlackDetail/NavBarBlackDetail',
    'pages/NavBarWhiteDetail/NavBarWhiteDetail',
    'pages/EditorDisplay/EditorDisplay',
    'pages/EditorDisplayDetail/EditorDisplayDetail',
    'pages/Mask/Mask',
    'pages/Filter/Filter',
    'pages/FloatingActionButton/FloatingActionButton',
    'pages/Title/Title',
    'pages/HighlightText/HighlightText',
    'pages/Card/Card',
    'pages/Steppers/Steppers',
  ],
  window: {
    backgroundTextStyle: 'light',
    navigationBarBackgroundColor: '#f8f8f8',
    navigationBarTitleText: 'WeChat',
    navigationBarTextStyle: 'black',
  },
} as Config
